import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { Toaster } from 'react-hot-toast';
=======
import Navbar from "@/components/Navbar";
>>>>>>> 8365263c955c863f7ab0e1f7254645740df7c4b4

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "iqm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <Toaster position="top-center" reverseOrder={false} />
=======
        <Navbar/>
>>>>>>> 8365263c955c863f7ab0e1f7254645740df7c4b4
        {children}
      </body>
    </html>
  );
}
